'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/AuthProvider';
import { usePreferences } from '@/components/PreferencesProvider';

type AdminExam={id:string;slug:string;titleEn:string;titleFa:string;level:string;durationMinutes:number;passingScore:number;startsAt:string;endsAt:string;published:boolean;questionCount:number;attempts:number;submitted:number};
type AdminAttempt={id:string;examTitle:string;studentName:string;studentEmail:string;status:string;startedAt:string;submittedAt:string|null;percentage:number|null;passed:boolean|null};
type AdminOverview={metrics:{exams:number;published:number;attempts:number;submitted:number;averagePercentage:number};exams:AdminExam[];attempts:AdminAttempt[]};
type Draft={published:boolean;startsAt:string;endsAt:string;durationMinutes:string;passingScore:string};

function inputDate(iso:string){const date=new Date(iso);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function draft(exam:AdminExam):Draft{return{published:exam.published,startsAt:inputDate(exam.startsAt),endsAt:inputDate(exam.endsAt),durationMinutes:String(exam.durationMinutes),passingScore:String(exam.passingScore)};}

export default function AdminExamsPage(){
  const {user,loading,logout,apiFetch}=useAuth();const {locale,t}=usePreferences();const router=useRouter();
  const [data,setData]=useState<AdminOverview|null>(null);const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const load=useCallback(()=>apiFetch<AdminOverview>('/api/v1/admin/exams').then(result=>{setData(result);setDrafts(Object.fromEntries(result.exams.map(exam=>[exam.id,draft(exam)])));}).catch(problem=>setError(problem.message)),[apiFetch]);
  useEffect(()=>{if(!loading&&(!user||user.role!=='ADMIN'))router.replace(user?'/dashboard':'/login');else if(user?.role==='ADMIN')load();},[loading,user,router,load]);
  function change(id:string,value:Partial<Draft>){setDrafts(current=>({...current,[id]:{...current[id],...value}}));}
  async function save(exam:AdminExam){const value=drafts[exam.id];setBusy(exam.id);setError('');try{await apiFetch(`/api/v1/admin/exams/${exam.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({published:value.published,startsAt:new Date(value.startsAt).toISOString(),endsAt:new Date(value.endsAt).toISOString(),durationMinutes:Number(value.durationMinutes),passingScore:Number(value.passingScore)})});await load();}catch(problem){setError(problem instanceof Error?problem.message:t('exam.failed'));}finally{setBusy('');}}
  async function signOut(){await logout();router.push('/');}
  if(loading||!user||!data)return <main className="status-page"><section><div className="status-orb">✓</div><p className="page-eyebrow">{t('exam.adminControl')}</p><h1>{error||t('exam.loadingAdmin')}</h1></section></main>;
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="wordmark" href="/"><span className="wordmark-glyph">EN</span><span>ENAcademy</span></Link><span className="admin-badge">ADMIN</span><nav><Link href="/admin">⌂ {t('admin.overview')}</Link><Link className="active" href="/admin/exams">✓ {t('exam.exams')}</Link><Link href="/admin/commerce">▤ {t('commerce.commerce')}</Link><Link href="/dashboard">↗ {t('admin.studentView')}</Link></nav><button className="admin-signout" onClick={signOut}>{t('admin.signOut')} ↗</button></aside>
    <section className="admin-main exam-admin-main"><header><div><p className="page-eyebrow">{t('exam.adminControl')}</p><h1>{t('exam.adminTitle')}</h1><p>{t('exam.adminLede')}</p></div><span className="admin-avatar">{user.fullName.slice(0,2).toUpperCase()}</span></header>{error&&<div className="commerce-error" role="alert">{error}</div>}
      <div className="admin-stats"><article><span>✓</span><div><strong>{data.metrics.exams}</strong><small>{t('exam.exams')}</small></div></article><article><span>◉</span><div><strong>{data.metrics.published}</strong><small>{t('exam.published')}</small></div></article><article><span>◎</span><div><strong>{data.metrics.attempts}</strong><small>{t('exam.attempts')}</small></div></article><article><span>↗</span><div><strong>{data.metrics.averagePercentage}%</strong><small>{t('exam.average')}</small></div></article></div>
      <section className="admin-table-section exam-schedule"><div><p className="page-eyebrow">{t('exam.schedule')}</p><h2>{t('exam.scheduleTitle')}</h2></div><div className="exam-admin-list">{data.exams.map(exam=>{const value=drafts[exam.id];return <article key={exam.id}><div className="exam-admin-title"><span>{exam.level}</span><div><strong>{locale==='fa'?exam.titleFa:exam.titleEn}</strong><small>{exam.questionCount} {t('exam.questions')} · {exam.submitted}/{exam.attempts} {t('exam.submittedCount')}</small></div></div><div className="exam-admin-fields"><label><span>{t('exam.starts')}</span><input type="datetime-local" value={value.startsAt} onChange={event=>change(exam.id,{startsAt:event.target.value})}/></label><label><span>{t('exam.ends')}</span><input type="datetime-local" value={value.endsAt} onChange={event=>change(exam.id,{endsAt:event.target.value})}/></label><label><span>{t('exam.duration')}</span><input type="number" min="5" max="240" value={value.durationMinutes} onChange={event=>change(exam.id,{durationMinutes:event.target.value})}/></label><label><span>{t('exam.passScore')}</span><input type="number" min="0" max="100" value={value.passingScore} onChange={event=>change(exam.id,{passingScore:event.target.value})}/></label></div><div className="exam-admin-actions"><label><input type="checkbox" checked={value.published} onChange={event=>change(exam.id,{published:event.target.checked})}/><span>{t('exam.published')}</span></label><button disabled={busy===exam.id} onClick={()=>save(exam)}>{busy===exam.id?t('commerce.saving'):t('commerce.save')}</button></div></article>;})}</div></section>
      <section className="admin-table-section exam-attempts"><div><p className="page-eyebrow">{t('exam.liveActivity')}</p><h2>{t('exam.recentAttempts')}</h2></div>{data.attempts.length?<div>{data.attempts.map(item=><article key={item.id}><span className={`attempt-dot ${item.status.toLowerCase()}`}>●</span><div><strong>{item.studentName}</strong><small>{item.studentEmail} · {item.examTitle}</small></div><time>{new Intl.DateTimeFormat(locale==='fa'?'fa-IR':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.startedAt))}</time><b>{item.percentage===null?t(`exam.status.${item.status.toLowerCase()}`):`${item.percentage}%`}</b></article>)}</div>:<div className="admin-empty"><span>✓</span><h3>{t('exam.noAttempts')}</h3><p>{t('exam.noAttemptsBody')}</p></div>}</section>
    </section>
  </main>;
}
