import Link from 'next/link';
import { requireChatGPTUser, chatGPTSignOutPath } from '@/app/chatgpt-auth';
import { ensureProfile, listStudents } from '@/db/academy';
import { AdminStudentActions } from '@/components/AdminStudentActions';

export const dynamic = 'force-dynamic';

export default async function AdminPage() {
  const user = await requireChatGPTUser('/admin');
  const profile = await ensureProfile(user);
  if (profile.role!=='admin'||profile.status!=='approved') return <main className="status-page"><section><div className="status-orb rejected">!</div><p className="page-eyebrow">RESTRICTED AREA</p><h1>Administrator access required.</h1><p>This identity is not configured as an ENAcademy administrator.</p><Link className="button button-ghost" href="/dashboard">Return to dashboard</Link></section></main>;
  const students=await listStudents(); const pending=students.filter((student)=>student.status==='pending'); const approved=students.filter((student)=>student.status==='approved');
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="wordmark" href="/"><span className="wordmark-glyph">EN</span><span>ENAcademy</span></Link><span className="admin-badge">ADMIN</span><nav><Link className="active" href="/admin">⌂ Overview</Link><a href="#applications">◎ Applications <b>{pending.length}</b></a><a href="#students">◉ Students</a><Link href="/dashboard">↗ Student view</Link></nav><Link className="admin-signout" href={chatGPTSignOutPath('/')}>Sign out ↗</Link></aside><section className="admin-main"><header><div><p className="page-eyebrow">CONTROL CENTER</p><h1>Keep the learning space healthy.</h1><p>Review new learners and manage access with a clear audit trail.</p></div><span className="admin-avatar">{profile.full_name.slice(0,2).toUpperCase()}</span></header><div className="admin-stats"><article><span>◎</span><div><strong>{pending.length}</strong><small>Pending review</small></div></article><article><span>✓</span><div><strong>{approved.length}</strong><small>Active students</small></div></article><article><span>◉</span><div><strong>{students.length}</strong><small>Total accounts</small></div></article><article><span>↗</span><div><strong>{students.filter((s)=>s.status==='suspended').length}</strong><small>Suspended</small></div></article></div><section className="admin-table-section" id="applications"><div><p className="page-eyebrow">APPLICATION QUEUE</p><h2>Students waiting for approval</h2></div>{pending.length?<div className="admin-table">{pending.map((student)=><article key={student.user_id}><span className="student-avatar">{student.full_name.slice(0,2).toUpperCase()}</span><div><strong>{student.full_name}</strong><small>{student.email}</small></div><time>{new Date(student.created_at).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})}</time><AdminStudentActions userId={student.user_id} currentStatus={student.status}/></article>)}</div>:<div className="admin-empty"><span>✓</span><h3>Queue clear</h3><p>Every student application has been reviewed.</p></div>}</section><section className="admin-table-section" id="students"><div><p className="page-eyebrow">ALL STUDENTS</p><h2>Account directory</h2></div><div className="admin-table compact">{students.map((student)=><article key={student.user_id}><span className="student-avatar">{student.full_name.slice(0,2).toUpperCase()}</span><div><strong>{student.full_name}</strong><small>{student.email}</small></div><span className={`status-pill ${student.status}`}>{student.status}</span><AdminStudentActions userId={student.user_id} currentStatus={student.status}/></article>)}</div></section></section></main>;
}
