export type Locale = 'en' | 'fa';

type Values = Record<string, string | number>;

const en: Record<string, string> = {
  'header.home': 'ENAcademy home', 'header.nav': 'Main navigation', 'header.how': 'How it works', 'header.curriculum': 'Curriculum', 'header.about': 'About us', 'header.signIn': 'Sign in', 'header.start': 'Start learning',
  'footer.tagline': 'English for real life—designed, built, and shared as a learning product experiment.', 'footer.explore': 'Explore', 'footer.studentLogin': 'Student login', 'footer.project': 'Project', 'footer.release': 'A1–A2 release', 'footer.portfolio': 'Portfolio build', 'footer.openSource': 'Open-source ready', 'footer.note': '© 2026 ENAcademy. Built to learn in public.',
  'prefs.language': 'Switch language', 'prefs.theme': 'Switch color mode', 'prefs.colors': 'Choose accent color', 'prefs.light': 'Light mode', 'prefs.dark': 'Dark mode', 'prefs.palette': 'Color palettes', 'prefs.emerald': 'Emerald', 'prefs.ocean': 'Ocean', 'prefs.violet': 'Violet', 'prefs.sunset': 'Sunset', 'prefs.rose': 'Rose',
  'home.hero.badge': 'Built for real conversations', 'home.hero.title1': 'Learn it. Live it.', 'home.hero.title2': 'Speak without translating.', 'home.hero.lede': 'A guided English journey that turns short daily practice into calm, natural conversation—from your first A1 phrase to confident A2 moments.', 'home.hero.start': 'Start your path', 'home.hero.see': 'See how it works', 'home.hero.complete': 'Complete path', 'home.hero.rhythm': 'Daily rhythm', 'home.hero.skills': '4 skills', 'home.hero.experience': 'One experience', 'home.hero.preview': 'Interactive learning preview', 'home.hero.today': "TODAY'S MOMENT", 'home.hero.speaking': 'Speaking', 'home.hero.confident': 'Confident', 'home.hero.listening': 'Listening', 'home.hero.voices': 'Real voices', 'home.hero.progress': 'Progress', 'home.hero.streak': '7 day streak', 'home.hero.keep': 'Keep the rhythm',
  'home.signals.label': 'One thoughtful system for', 'home.signals.everyday': 'Everyday English', 'home.signals.pronunciation': 'Clear pronunciation', 'home.signals.progress': 'Visible progress', 'home.signals.vocabulary': 'Lasting vocabulary',
  'home.method.eyebrow': 'A BETTER DAILY LOOP', 'home.method.title': 'Every lesson ends in something you can actually say.', 'home.method.lede': 'ENAcademy connects the four skills instead of teaching them in isolation. Hear the moment, notice the language, prove you understand it, then use your own voice.', 'home.method.one.title': 'Hear the moment', 'home.method.one.body': 'Start inside a short, realistic conversation and train your ear for meaning and rhythm.', 'home.method.two.title': 'See the pattern', 'home.method.two.body': 'Collect useful words and discover one practical grammar pattern without the textbook fog.', 'home.method.three.title': 'Make it yours', 'home.method.three.body': 'Answer a focused check, speak the phrase aloud, and save durable progress to your account.',
  'home.showcase.eyebrow': 'A LEARNING SPACE, NOT A SCOREBOARD', 'home.showcase.title1': 'Calm enough to return to.', 'home.showcase.title2': 'Powerful enough to grow with.', 'home.showcase.body': 'Your dashboard turns the complete A1–A2 journey into one clear next step. Lessons unlock in sequence, saved words stay with you, and progress reflects completed work—not meaningless taps.', 'home.showcase.point1': 'Personal learning path and next lesson', 'home.showcase.point2': 'XP, completion, accuracy, and word bank', 'home.showcase.point3': 'Account approval and secure role access', 'home.showcase.cta': 'See your dashboard', 'home.showcase.space': 'YOUR LEARNING SPACE', 'home.showcase.greeting': 'Good afternoon, learner.', 'home.showcase.next': 'NEXT UP · A2', 'home.showcase.lesson': 'Make weekend plans', 'home.showcase.objective': 'Turn future grammar into a real invitation.', 'home.showcase.continue': 'Continue lesson',
  'home.course.eyebrow': 'THE FIRST COMPLETE PATH', 'home.course.title': 'Two levels. Eight milestones. Sixteen useful moments.', 'home.course.body': 'A focused route from your first introduction to independent A2 conversations.', 'home.course.a1': 'FOUNDATIONS', 'home.course.a1title': 'Build reliable everyday English', 'home.course.a1body': 'Introductions · routines · cafés · shopping · directions · travel', 'home.course.a2': 'EVERYDAY FLUENCY', 'home.course.a2title': 'Turn knowledge into your own voice', 'home.course.a2body': 'Plans · invitations · stories · work · problems · opinions · goals', 'home.course.lessons': '8 interactive lessons', 'home.course.cta': 'Explore the complete curriculum',
  'home.roles.application': 'Student application', 'home.roles.new': 'New', 'home.roles.approve': 'Approve', 'home.roles.review': 'Review', 'home.roles.approved': 'Access approved', 'home.roles.eyebrow': 'THOUGHTFUL ACCESS', 'home.roles.title': 'Students join freely. Admins keep the space intentional.', 'home.roles.body': 'New learners create a secure identity and enter a clear approval queue. The administrator can approve, reject, or suspend access while student progress remains protected on the server.', 'home.roles.student': 'Student account', 'home.roles.studentBody': 'Sign in securely and request course access.', 'home.roles.admin': 'Admin review', 'home.roles.adminBody': 'Approve the learner from a dedicated control center.', 'home.roles.durable': 'Durable learning', 'home.roles.durableBody': 'Lessons, XP, scores, and saved words persist.',
  'home.about.eyebrow': 'A PROJECT WITH A POINT OF VIEW', 'home.about.quote': '“Build the English product you wish learning apps felt like.”', 'home.about.body': 'ENAcademy is a portfolio-grade product experiment spanning strategy, interface design, curriculum modeling, full-stack engineering, authentication, and data. It is being prepared for a future open-source release.', 'home.about.cta': 'Read the story behind ENAcademy', 'home.final.eyebrow': 'YOUR FIRST MOMENT IS READY', 'home.final.title1': 'Less translating.', 'home.final.title2': 'More living.', 'home.final.body': 'Start with a secure student account and twelve focused minutes.', 'home.final.cta': 'Begin your English path',
  'about.eyebrow': 'ABOUT THE EXPERIMENT', 'about.title': 'A serious learning product, built as a public test of craft.', 'about.lede': 'ENAcademy began as a portfolio challenge: design an English platform that feels calm, useful, and complete—not another collection of disconnected exercises.', 'about.why': 'WHY IT EXISTS', 'about.manifesto': 'Learning should move from knowing to doing.', 'about.p1': 'Traditional apps can make learners good at tapping answers while real conversations still feel difficult. ENAcademy organizes every lesson around a moment you may genuinely face: meeting someone, ordering lunch, solving a problem, sharing an opinion.', 'about.p2': 'Vocabulary, grammar, listening, and speaking are taught together so each new pattern becomes something you can use—not just recognize.', 'about.principle1': 'Context before complexity', 'about.principle1body': 'Every skill begins inside a believable conversation, then reveals the language underneath it.', 'about.principle2': 'Small wins, visible growth', 'about.principle2body': 'Short sessions, saved progress, clear milestones, and honest feedback make consistency feel possible.', 'about.principle3': 'Voice before perfection', 'about.principle3body': 'Speaking practice starts early. Learners build courage while accuracy grows naturally.', 'about.open': 'BUILT IN THE OPEN', 'about.openTitle': 'A portfolio project with product-level ambition.', 'about.openBody': 'This release demonstrates product strategy, interface design, full-stack engineering, curriculum modeling, accessibility, authentication, and durable data. The codebase is being prepared for a future open-source release so other builders can study it, extend it, and improve it.', 'about.explore': 'Explore the curriculum', 'about.ready': 'READY WHEN YOU ARE', 'about.readyTitle': 'Your next English moment starts here.', 'about.create': 'Create your student account',
  'curriculum.eyebrow': 'THE COMPLETE FIRST RELEASE', 'curriculum.title': 'From first hello to independent voice.', 'curriculum.lede': 'Sixteen practical lessons, eight real-life units, and one connected A1–A2 journey. Every lesson moves through listening, vocabulary, grammar, a knowledge check, and guided speaking.', 'curriculum.lessons': 'interactive lessons', 'curriculum.words': 'high-utility words', 'curriculum.steps': 'learning steps', 'curriculum.levels': 'CEFR levels', 'curriculum.foundations': 'FOUNDATIONS', 'curriculum.fluency': 'EVERYDAY FLUENCY', 'curriculum.a1Title': 'Build your first reliable English', 'curriculum.a2Title': 'Turn knowledge into independent conversation', 'curriculum.outcome': 'OUTCOME', 'curriculum.lessonCount': '{count} lessons', 'curriculum.ready': 'YOUR PATH IS READY', 'curriculum.readyTitle': 'Start with twelve focused minutes.', 'curriculum.create': 'Create your account',
  'auth.welcome': 'WELCOME TO ENACADEMY', 'auth.title': 'Your English starts here.', 'auth.lede': 'Create a secure student profile or continue your learning path. Administrator permissions are assigned by the platform, never selected in the browser.', 'auth.signIn': 'Sign in', 'auth.create': 'Create account', 'auth.back': 'WELCOME BACK', 'auth.application': 'STUDENT APPLICATION', 'auth.continue': 'Continue your progress.', 'auth.profile': 'Build your learner profile.', 'auth.name': 'Full name', 'auth.namePlaceholder': 'Your full name', 'auth.email': 'Email address', 'auth.password': 'Password', 'auth.passwordPlaceholder': 'At least 10 characters', 'auth.passwordHelp': 'Use uppercase, lowercase, and at least one number.', 'auth.wait': 'Please wait…', 'auth.secure': 'Sign in securely', 'auth.createStudent': 'Create student account', 'auth.localMail': 'In local Docker, open Mailpit at localhost:8025.', 'auth.failed': 'Unable to continue.', 'auth.validationFailed': 'Please correct the fields below.', 'auth.nameInvalid': 'Enter a name between 2 and 120 characters.', 'auth.emailInvalid': 'Enter a valid email address.', 'auth.passwordInvalid': 'Use 10–72 characters with uppercase, lowercase, and at least one number.', 'auth.passwordRequired': 'Enter your password.', 'auth.trusted': 'TRUSTED ACCESS', 'auth.workflow': 'A real approval workflow.', 'auth.workflowBody': 'Every learner passes three clear checkpoints before course access opens.', 'auth.step1': 'Create your account', 'auth.step1body': 'Your password is securely hashed.', 'auth.step2': 'Verify your email', 'auth.step2body': 'Use the one-time link sent to your inbox.', 'auth.step3': 'Administrator review', 'auth.step3body': 'An admin approves your student profile.', 'auth.admin': 'Administrator?', 'auth.adminBody': 'Use the same secure sign-in. Your server-assigned role opens the admin panel automatically.',
  'verify.workingMessage': 'Verifying your secure link…', 'verify.missing': 'The verification token is missing.', 'verify.invalid': 'This link is invalid or expired.', 'verify.eyebrow': 'EMAIL VERIFICATION', 'verify.working': 'One moment.', 'verify.done': 'Email verified.', 'verify.error': 'We could not verify this link.', 'verify.continue': 'Continue to sign in',
  'dashboard.preparing': 'Preparing your learning space…', 'dashboard.overview': 'Overview', 'dashboard.path': 'Learning path', 'dashboard.skills': 'My skills', 'dashboard.words': 'Saved words', 'dashboard.admin': 'Admin panel', 'dashboard.space': 'YOUR LEARNING SPACE', 'dashboard.greeting': 'Good to see you, {name}.', 'dashboard.rhythm': 'Keep the rhythm small and the progress real.', 'dashboard.learning': 'Learning', 'dashboard.dayOne': 'Day one', 'dashboard.next': 'NEXT UP', 'dashboard.minutes': '{count} min', 'dashboard.activities': '5 activities', 'dashboard.continue': 'Continue learning', 'dashboard.start': 'Start first lesson', 'dashboard.yourPath': 'YOUR PATH', 'dashboard.complete': '{done} of {total} complete', 'dashboard.pathEyebrow': 'LEARNING PATH', 'dashboard.milestones': 'Eight real-life milestones', 'dashboard.full': 'View full curriculum', 'dashboard.unit': 'UNIT {unit}', 'dashboard.vocabulary': 'VOCABULARY', 'dashboard.wordsSaved': '{count} words saved', 'dashboard.speaking': 'SPEAKING', 'dashboard.moments': '{count} guided moments', 'dashboard.knowledge': 'KNOWLEDGE', 'dashboard.average': '{count}% average',
  'admin.control': 'ADMIN CONTROL', 'admin.loading': 'Loading the approval queue…', 'admin.overview': 'Overview', 'admin.applications': 'Applications', 'admin.students': 'Students', 'admin.studentView': 'Student view', 'admin.signOut': 'Sign out', 'admin.center': 'CONTROL CENTER', 'admin.title': 'Keep the learning space healthy.', 'admin.lede': 'Review verified learners and manage access with a durable audit trail.', 'admin.pending': 'Pending review', 'admin.active': 'Active students', 'admin.total': 'Total accounts', 'admin.completed': 'Lessons completed', 'admin.queue': 'APPLICATION QUEUE', 'admin.waiting': 'Students waiting for approval', 'admin.clear': 'Queue clear', 'admin.clearBody': 'Every verified student application has been reviewed.', 'admin.all': 'ALL STUDENTS', 'admin.directory': 'Account directory', 'admin.unverified': 'email unverified', 'admin.approve': 'Approve', 'admin.suspend': 'Suspend', 'admin.reject': 'Reject', 'admin.status.pending': 'pending', 'admin.status.approved': 'approved', 'admin.status.rejected': 'rejected', 'admin.status.suspended': 'suspended',
  'lesson.unavailable': 'LESSON UNAVAILABLE', 'lesson.locked': 'Complete the earlier lessons to unlock this one.', 'lesson.return': 'Return to your path', 'lesson.lab': 'LESSON LAB', 'lesson.preparing': 'Preparing your lesson…', 'lesson.listen': 'Listen', 'lesson.words': 'Words', 'lesson.grammar': 'Grammar', 'lesson.check': 'Check', 'lesson.speak': 'Speak', 'lesson.complete': 'Complete', 'lesson.context': 'LISTEN IN CONTEXT', 'lesson.listenTo': 'Listen to {name}', 'lesson.notice': 'Notice the rhythm', 'lesson.noticeBody': 'Listen once for meaning, then again for the stressed words.', 'lesson.wordBank': 'BUILD YOUR WORD BANK', 'lesson.fourWords': 'Four words you can use today', 'lesson.hear': 'Hear it', 'lesson.pattern': 'PATTERN, NOT RULEBOOK', 'lesson.quick': 'QUICK CHECK', 'lesson.correct': 'Exactly right.', 'lesson.retry': 'Almost—look at the pattern again.', 'lesson.checkAnswer': 'Check answer', 'lesson.speakYourself': 'SPEAK IT YOURSELF', 'lesson.voice': 'Turn the pattern into your voice', 'lesson.listening': 'Listening…', 'lesson.startSpeaking': 'Start speaking', 'lesson.weHeard': 'WE HEARD', 'lesson.match': '{count}% phrase match', 'lesson.recognitionUnavailable': 'Speech recognition is not available in this browser. You can still listen and repeat aloud.', 'lesson.completed': 'LESSON COMPLETE', 'lesson.action': 'You turned English into action.', 'lesson.saved': 'Your progress is saved. Keep the momentum going.', 'lesson.saving': 'Saving your progress…', 'lesson.xp': 'XP EARNED', 'lesson.knowledge': 'KNOWLEDGE CHECK', 'lesson.review': 'Review', 'lesson.practice': 'FOCUSED PRACTICE', 'lesson.continuePath': 'Continue your path', 'lesson.back': 'Back', 'lesson.continue': 'Continue',
};

const fa: Record<string, string> = {
  'header.home': 'صفحه اصلی ENAcademy', 'header.nav': 'منوی اصلی', 'header.how': 'روش یادگیری', 'header.curriculum': 'مسیر آموزشی', 'header.about': 'درباره ما', 'header.signIn': 'ورود', 'header.start': 'شروع یادگیری',
  'footer.tagline': 'انگلیسی برای زندگی واقعی؛ طراحی و ساخته‌شده به‌عنوان یک تجربه کامل یادگیری.', 'footer.explore': 'کاوش', 'footer.studentLogin': 'ورود زبان‌آموز', 'footer.project': 'پروژه', 'footer.release': 'نسخه A1 تا A2', 'footer.portfolio': 'پروژه نمونه‌کار', 'footer.openSource': 'آماده متن‌باز شدن', 'footer.note': '© ۲۰۲۶ ENAcademy. ساخته‌شده برای یادگیری در فضای باز.',
  'prefs.language': 'تغییر زبان', 'prefs.theme': 'تغییر حالت نمایش', 'prefs.colors': 'انتخاب رنگ اصلی', 'prefs.light': 'حالت روشن', 'prefs.dark': 'حالت تاریک', 'prefs.palette': 'پالت‌های رنگی', 'prefs.emerald': 'زمردی', 'prefs.ocean': 'اقیانوسی', 'prefs.violet': 'بنفش', 'prefs.sunset': 'غروب', 'prefs.rose': 'رز',
  'home.hero.badge': 'ساخته‌شده برای گفت‌وگوهای واقعی', 'home.hero.title1': 'یاد بگیر. زندگی کن.', 'home.hero.title2': 'بدون ترجمه صحبت کن.', 'home.hero.lede': 'یک مسیر هدایت‌شده انگلیسی که تمرین کوتاه روزانه را به گفت‌وگویی آرام و طبیعی تبدیل می‌کند؛ از نخستین عبارت A1 تا موقعیت‌های مطمئن A2.', 'home.hero.start': 'مسیرت را شروع کن', 'home.hero.see': 'روش کار را ببین', 'home.hero.complete': 'مسیر کامل', 'home.hero.rhythm': 'ریتم روزانه', 'home.hero.skills': '۴ مهارت', 'home.hero.experience': 'یک تجربه', 'home.hero.preview': 'پیش‌نمایش یادگیری تعاملی', 'home.hero.today': 'عبارت امروز', 'home.hero.speaking': 'مکالمه', 'home.hero.confident': 'با اعتمادبه‌نفس', 'home.hero.listening': 'شنیدن', 'home.hero.voices': 'صدای واقعی', 'home.hero.progress': 'پیشرفت', 'home.hero.streak': '۷ روز پیوسته', 'home.hero.keep': 'ریتمت را حفظ کن',
  'home.signals.label': 'یک سیستم هدفمند برای', 'home.signals.everyday': 'انگلیسی روزمره', 'home.signals.pronunciation': 'تلفظ روشن', 'home.signals.progress': 'پیشرفت قابل مشاهده', 'home.signals.vocabulary': 'واژگان ماندگار',
  'home.method.eyebrow': 'چرخه روزانه بهتر', 'home.method.title': 'هر درس با جمله‌ای تمام می‌شود که واقعاً می‌توانی بگویی.', 'home.method.lede': 'ENAcademy چهار مهارت را به‌جای آموزش جداگانه به هم متصل می‌کند. موقعیت را بشنو، الگو را ببین، درکت را بسنج و بعد با صدای خودت استفاده کن.', 'home.method.one.title': 'موقعیت را بشنو', 'home.method.one.body': 'از یک گفت‌وگوی کوتاه و واقعی شروع کن و گوشت را برای معنا و ریتم آموزش بده.', 'home.method.two.title': 'الگو را ببین', 'home.method.two.body': 'واژه‌های کاربردی را جمع کن و یک الگوی دستور زبان عملی را بدون پیچیدگی کتاب‌ها کشف کن.', 'home.method.three.title': 'آن را مال خودت کن', 'home.method.three.body': 'به یک پرسش دقیق پاسخ بده، عبارت را بلند بگو و پیشرفت پایدار را در حسابت ذخیره کن.',
  'home.showcase.eyebrow': 'فضای یادگیری، نه جدول امتیاز', 'home.showcase.title1': 'آن‌قدر آرام که برگردی.', 'home.showcase.title2': 'آن‌قدر قدرتمند که رشد کنی.', 'home.showcase.body': 'داشبورد، مسیر کامل A1 تا A2 را به یک قدم روشن بعدی تبدیل می‌کند. درس‌ها به‌ترتیب باز می‌شوند، واژه‌ها می‌مانند و پیشرفت از کار واقعی می‌آید.', 'home.showcase.point1': 'مسیر شخصی و درس بعدی', 'home.showcase.point2': 'XP، تکمیل، دقت و بانک واژگان', 'home.showcase.point3': 'تأیید حساب و دسترسی امن', 'home.showcase.cta': 'داشبوردت را ببین', 'home.showcase.space': 'فضای یادگیری تو', 'home.showcase.greeting': 'عصر بخیر، زبان‌آموز.', 'home.showcase.next': 'درس بعدی · A2', 'home.showcase.lesson': 'برنامه‌ریزی آخر هفته', 'home.showcase.objective': 'گرامر آینده را به یک دعوت واقعی تبدیل کن.', 'home.showcase.continue': 'ادامه درس',
  'home.course.eyebrow': 'نخستین مسیر کامل', 'home.course.title': 'دو سطح، هشت مرحله و شانزده موقعیت کاربردی.', 'home.course.body': 'مسیری متمرکز از نخستین معرفی تا گفت‌وگوی مستقل A2.', 'home.course.a1': 'پایه‌ها', 'home.course.a1title': 'انگلیسی روزمره قابل اتکا بساز', 'home.course.a1body': 'معرفی · کارهای روزمره · کافه · خرید · مسیر · سفر', 'home.course.a2': 'روانی روزمره', 'home.course.a2title': 'دانشت را به صدای خودت تبدیل کن', 'home.course.a2body': 'برنامه · دعوت · داستان · کار · مشکل · نظر · هدف', 'home.course.lessons': '۸ درس تعاملی', 'home.course.cta': 'مشاهده مسیر آموزشی کامل',
  'home.roles.application': 'درخواست زبان‌آموز', 'home.roles.new': 'جدید', 'home.roles.approve': 'تأیید', 'home.roles.review': 'بررسی', 'home.roles.approved': 'دسترسی تأیید شد', 'home.roles.eyebrow': 'دسترسی هدفمند', 'home.roles.title': 'زبان‌آموزان آزادانه ثبت‌نام می‌کنند؛ مدیر فضا را مدیریت می‌کند.', 'home.roles.body': 'زبان‌آموز هویت امن می‌سازد و وارد صف بررسی می‌شود. مدیر می‌تواند دسترسی را تأیید، رد یا تعلیق کند و پیشرفت روی سرور محفوظ می‌ماند.', 'home.roles.student': 'حساب زبان‌آموز', 'home.roles.studentBody': 'امن وارد شو و درخواست دسترسی بده.', 'home.roles.admin': 'بررسی مدیر', 'home.roles.adminBody': 'زبان‌آموز را از مرکز کنترل اختصاصی تأیید کن.', 'home.roles.durable': 'یادگیری پایدار', 'home.roles.durableBody': 'درس‌ها، XP، نمره‌ها و واژه‌ها ذخیره می‌شوند.',
  'home.about.eyebrow': 'پروژه‌ای با دیدگاه مشخص', 'home.about.quote': '«محصول آموزش انگلیسی‌ای را بساز که دوست داشتی وجود داشته باشد.»', 'home.about.body': 'ENAcademy یک تجربه محصول در سطح نمونه‌کار است که راهبرد، طراحی رابط، مدل‌سازی محتوا، مهندسی فول‌استک، احراز هویت و داده را کنار هم می‌آورد.', 'home.about.cta': 'داستان ENAcademy را بخوان', 'home.final.eyebrow': 'اولین موقعیت تو آماده است', 'home.final.title1': 'ترجمه کمتر.', 'home.final.title2': 'زندگی بیشتر.', 'home.final.body': 'با یک حساب امن و دوازده دقیقه تمرکز شروع کن.', 'home.final.cta': 'مسیر انگلیسی را شروع کن',
  'about.eyebrow': 'درباره این تجربه', 'about.title': 'یک محصول جدی یادگیری؛ ساخته‌شده برای نمایش عمومی مهارت.', 'about.lede': 'ENAcademy با یک چالش نمونه‌کار شروع شد: ساخت پلتفرمی آرام، کاربردی و کامل؛ نه مجموعه‌ای از تمرین‌های جدا.', 'about.why': 'چرا ساخته شد', 'about.manifesto': 'یادگیری باید از دانستن به انجام‌دادن برسد.', 'about.p1': 'اپ‌های سنتی ممکن است ما را در لمس پاسخ‌ها ماهر کنند، اما گفت‌وگوی واقعی هنوز سخت بماند. هر درس ENAcademy پیرامون موقعیتی واقعی طراحی شده است.', 'about.p2': 'واژگان، دستور زبان، شنیدن و صحبت‌کردن کنار هم آموزش داده می‌شوند تا هر الگو قابل استفاده باشد، نه فقط قابل تشخیص.', 'about.principle1': 'زمینه پیش از پیچیدگی', 'about.principle1body': 'هر مهارت درون یک گفت‌وگوی باورپذیر شروع می‌شود و بعد زبان زیر آن را نشان می‌دهد.', 'about.principle2': 'بردهای کوچک، رشد روشن', 'about.principle2body': 'جلسه‌های کوتاه، پیشرفت ذخیره‌شده و بازخورد صادقانه، استمرار را ممکن می‌کند.', 'about.principle3': 'صدا پیش از بی‌نقصی', 'about.principle3body': 'تمرین صحبت‌کردن زود شروع می‌شود؛ شجاعت رشد می‌کند و دقت طبیعی‌تر می‌شود.', 'about.open': 'ساخته‌شده در فضای باز', 'about.openTitle': 'پروژه نمونه‌کار با جاه‌طلبی یک محصول واقعی.', 'about.openBody': 'این نسخه راهبرد محصول، طراحی رابط، مهندسی فول‌استک، دسترس‌پذیری، احراز هویت و داده پایدار را نمایش می‌دهد و برای انتشار متن‌باز آینده آماده می‌شود.', 'about.explore': 'مشاهده مسیر آموزشی', 'about.ready': 'هر زمان آماده‌ای', 'about.readyTitle': 'موقعیت بعدی انگلیسی تو از اینجا شروع می‌شود.', 'about.create': 'ساخت حساب زبان‌آموز',
  'curriculum.eyebrow': 'نخستین نسخه کامل', 'curriculum.title': 'از اولین سلام تا صدای مستقل.', 'curriculum.lede': 'شانزده درس عملی، هشت واحد واقعی و یک مسیر پیوسته A1 تا A2. هر درس شامل شنیدن، واژگان، دستور زبان، سنجش و گفتار هدایت‌شده است.', 'curriculum.lessons': 'درس تعاملی', 'curriculum.words': 'واژه پرکاربرد', 'curriculum.steps': 'مرحله یادگیری', 'curriculum.levels': 'سطح CEFR', 'curriculum.foundations': 'پایه‌ها', 'curriculum.fluency': 'روانی روزمره', 'curriculum.a1Title': 'اولین انگلیسی قابل اتکایت را بساز', 'curriculum.a2Title': 'دانش را به گفت‌وگوی مستقل تبدیل کن', 'curriculum.outcome': 'دستاورد', 'curriculum.lessonCount': '{count} درس', 'curriculum.ready': 'مسیر تو آماده است', 'curriculum.readyTitle': 'با دوازده دقیقه تمرکز شروع کن.', 'curriculum.create': 'ساخت حساب',
  'auth.welcome': 'به ENAcademy خوش آمدی', 'auth.title': 'انگلیسی تو از اینجا شروع می‌شود.', 'auth.lede': 'یک پروفایل امن بساز یا مسیر یادگیری را ادامه بده. دسترسی مدیر فقط روی سرور تعیین می‌شود.', 'auth.signIn': 'ورود', 'auth.create': 'ساخت حساب', 'auth.back': 'خوش برگشتی', 'auth.application': 'درخواست زبان‌آموز', 'auth.continue': 'پیشرفتت را ادامه بده.', 'auth.profile': 'پروفایل یادگیری‌ات را بساز.', 'auth.name': 'نام کامل', 'auth.namePlaceholder': 'نام و نام خانوادگی', 'auth.email': 'نشانی ایمیل', 'auth.password': 'رمز عبور', 'auth.passwordPlaceholder': 'حداقل ۱۰ نویسه', 'auth.passwordHelp': 'از حروف بزرگ، کوچک و حداقل یک عدد استفاده کن.', 'auth.wait': 'لطفاً صبر کن…', 'auth.secure': 'ورود امن', 'auth.createStudent': 'ساخت حساب زبان‌آموز', 'auth.localMail': 'در Docker محلی، Mailpit را در localhost:8025 باز کن.', 'auth.failed': 'ادامه ممکن نشد.', 'auth.validationFailed': 'لطفاً موارد مشخص‌شده را اصلاح کن.', 'auth.nameInvalid': 'نام باید بین ۲ تا ۱۲۰ نویسه باشد.', 'auth.emailInvalid': 'یک نشانی ایمیل معتبر وارد کن.', 'auth.passwordInvalid': 'رمز عبور باید ۱۰ تا ۷۲ نویسه و شامل حرف بزرگ، حرف کوچک و عدد باشد.', 'auth.passwordRequired': 'رمز عبور را وارد کن.', 'auth.trusted': 'دسترسی قابل اعتماد', 'auth.workflow': 'فرآیند تأیید واقعی.', 'auth.workflowBody': 'هر زبان‌آموز پیش از ورود به دوره سه مرحله روشن را طی می‌کند.', 'auth.step1': 'حسابت را بساز', 'auth.step1body': 'رمز عبور به‌صورت امن هش می‌شود.', 'auth.step2': 'ایمیلت را تأیید کن', 'auth.step2body': 'از پیوند یک‌بارمصرف ایمیل استفاده کن.', 'auth.step3': 'بررسی مدیر', 'auth.step3body': 'مدیر پروفایل زبان‌آموز را تأیید می‌کند.', 'auth.admin': 'مدیر هستی؟', 'auth.adminBody': 'از همین ورود امن استفاده کن؛ نقش ثبت‌شده روی سرور پنل مدیر را باز می‌کند.',
  'verify.workingMessage': 'در حال بررسی پیوند امن…', 'verify.missing': 'توکن تأیید وجود ندارد.', 'verify.invalid': 'این پیوند نامعتبر یا منقضی شده است.', 'verify.eyebrow': 'تأیید ایمیل', 'verify.working': 'یک لحظه صبر کن.', 'verify.done': 'ایمیل تأیید شد.', 'verify.error': 'نتوانستیم این پیوند را تأیید کنیم.', 'verify.continue': 'ادامه برای ورود',
  'dashboard.preparing': 'در حال آماده‌سازی فضای یادگیری…', 'dashboard.overview': 'نمای کلی', 'dashboard.path': 'مسیر یادگیری', 'dashboard.skills': 'مهارت‌های من', 'dashboard.words': 'واژه‌های ذخیره‌شده', 'dashboard.admin': 'پنل مدیر', 'dashboard.space': 'فضای یادگیری تو', 'dashboard.greeting': 'از دیدنت خوشحالیم، {name}.', 'dashboard.rhythm': 'ریتم را کوچک و پیشرفت را واقعی نگه دار.', 'dashboard.learning': 'در حال یادگیری', 'dashboard.dayOne': 'روز اول', 'dashboard.next': 'درس بعدی', 'dashboard.minutes': '{count} دقیقه', 'dashboard.activities': '۵ فعالیت', 'dashboard.continue': 'ادامه یادگیری', 'dashboard.start': 'شروع اولین درس', 'dashboard.yourPath': 'مسیر تو', 'dashboard.complete': '{done} از {total} کامل', 'dashboard.pathEyebrow': 'مسیر یادگیری', 'dashboard.milestones': 'هشت مرحله واقعی', 'dashboard.full': 'مشاهده مسیر کامل', 'dashboard.unit': 'واحد {unit}', 'dashboard.vocabulary': 'واژگان', 'dashboard.wordsSaved': '{count} واژه ذخیره‌شده', 'dashboard.speaking': 'مکالمه', 'dashboard.moments': '{count} تمرین هدایت‌شده', 'dashboard.knowledge': 'دانش', 'dashboard.average': 'میانگین {count}٪',
  'admin.control': 'کنترل مدیر', 'admin.loading': 'در حال بارگذاری صف تأیید…', 'admin.overview': 'نمای کلی', 'admin.applications': 'درخواست‌ها', 'admin.students': 'زبان‌آموزان', 'admin.studentView': 'نمای زبان‌آموز', 'admin.signOut': 'خروج', 'admin.center': 'مرکز کنترل', 'admin.title': 'فضای یادگیری را سالم نگه دار.', 'admin.lede': 'زبان‌آموزان تأییدشده را بررسی و دسترسی را با تاریخچه پایدار مدیریت کن.', 'admin.pending': 'در انتظار بررسی', 'admin.active': 'زبان‌آموز فعال', 'admin.total': 'کل حساب‌ها', 'admin.completed': 'درس‌های کامل‌شده', 'admin.queue': 'صف درخواست‌ها', 'admin.waiting': 'زبان‌آموزان منتظر تأیید', 'admin.clear': 'صف خالی است', 'admin.clearBody': 'تمام درخواست‌های تأییدشده بررسی شده‌اند.', 'admin.all': 'همه زبان‌آموزان', 'admin.directory': 'فهرست حساب‌ها', 'admin.unverified': 'ایمیل تأیید نشده', 'admin.approve': 'تأیید', 'admin.suspend': 'تعلیق', 'admin.reject': 'رد', 'admin.status.pending': 'در انتظار', 'admin.status.approved': 'تأییدشده', 'admin.status.rejected': 'ردشده', 'admin.status.suspended': 'تعلیق‌شده',
  'lesson.unavailable': 'درس در دسترس نیست', 'lesson.locked': 'برای بازشدن این درس، درس‌های قبلی را کامل کن.', 'lesson.return': 'بازگشت به مسیر', 'lesson.lab': 'آزمایشگاه درس', 'lesson.preparing': 'در حال آماده‌سازی درس…', 'lesson.listen': 'شنیدن', 'lesson.words': 'واژه‌ها', 'lesson.grammar': 'دستور زبان', 'lesson.check': 'سنجش', 'lesson.speak': 'گفتار', 'lesson.complete': 'تکمیل', 'lesson.context': 'شنیدن در موقعیت', 'lesson.listenTo': 'شنیدن صدای {name}', 'lesson.notice': 'به ریتم توجه کن', 'lesson.noticeBody': 'یک بار برای معنا و بار دوم برای واژه‌های تأکیدی گوش بده.', 'lesson.wordBank': 'ساخت بانک واژگان', 'lesson.fourWords': 'چهار واژه برای استفاده امروز', 'lesson.hear': 'بشنو', 'lesson.pattern': 'الگو، نه کتاب قانون', 'lesson.quick': 'سنجش سریع', 'lesson.correct': 'کاملاً درست است.', 'lesson.retry': 'نزدیک بود؛ دوباره الگو را ببین.', 'lesson.checkAnswer': 'بررسی پاسخ', 'lesson.speakYourself': 'خودت بگو', 'lesson.voice': 'الگو را به صدای خودت تبدیل کن', 'lesson.listening': 'در حال شنیدن…', 'lesson.startSpeaking': 'شروع صحبت', 'lesson.weHeard': 'آنچه شنیدیم', 'lesson.match': '{count}٪ تطابق عبارت', 'lesson.recognitionUnavailable': 'تشخیص گفتار در این مرورگر موجود نیست؛ همچنان می‌توانی گوش بدهی و بلند تکرار کنی.', 'lesson.completed': 'درس کامل شد', 'lesson.action': 'انگلیسی را به عمل تبدیل کردی.', 'lesson.saved': 'پیشرفتت ذخیره شد؛ حرکت را ادامه بده.', 'lesson.saving': 'در حال ذخیره پیشرفت…', 'lesson.xp': 'XP دریافت‌شده', 'lesson.knowledge': 'سنجش دانش', 'lesson.review': 'مرور', 'lesson.practice': 'تمرین متمرکز', 'lesson.continuePath': 'ادامه مسیر', 'lesson.back': 'بازگشت', 'lesson.continue': 'ادامه',
};

const persianModules: Record<string, { title: string; description: string; outcome: string }> = {
  'a1-connect': { title: 'شروع ارتباط', description: 'سلام، معرفی و احساسات.', outcome: 'با کسی آشنا شو و نخستین گفت‌وگوی کوتاه را پیش ببر.' },
  'a1-everyday': { title: 'زندگی روزمره تو', description: 'روتین، زمان، سرگرمی و ترجیح‌ها.', outcome: 'یک روز عادی و علاقه‌هایت را توصیف کن.' },
  'a1-out-about': { title: 'بیرون از خانه', description: 'کافه، خرید، قیمت و درخواست مؤدبانه.', outcome: 'بدون تغییر زبان سفارش بده و خرید کن.' },
  'a1-move': { title: 'حرکت در شهر', description: 'مسیر، حمل‌ونقل، ایستگاه و سفر.', outcome: 'راهت را پیدا کن و یک سفر ساده را مدیریت کن.' },
  'a2-plans': { title: 'برنامه‌ها و آدم‌ها', description: 'دعوت، هماهنگی و برنامه آینده.', outcome: 'برنامه بساز و طبیعی پاسخ بده.' },
  'a2-stories': { title: 'داستان‌ها و تجربه‌ها', description: 'رویداد گذشته و لحظه‌های به‌یادماندنی.', outcome: 'یک داستان کوتاه و روشن تعریف کن.' },
  'a2-work': { title: 'انگلیسی کاربردی', description: 'درخواست، شفاف‌سازی، مهلت و مشکل.', outcome: 'گفت‌وگوهای کاری رایج را آرام مدیریت کن.' },
  'a2-voice': { title: 'صدای مستقل تو', description: 'نظر، تضاد، هدف و قدم بعدی.', outcome: 'فکرت و مسیر آینده‌ات را بیان کن.' },
};

const persianLessons: Record<string, { title: string; objective: string }> = {
  'a1-first-hello': { title: 'اولین سلام تو', objective: 'خودت را معرفی کن و طبیعی سلام بده.' }, 'a1-how-are-you': { title: 'حالت چطور است؟', objective: 'احوال کسی را بپرس و با بیش از یک واژه پاسخ بده.' },
  'a1-daily-routine': { title: 'برنامه روزمره من', objective: 'یک روز کاری ساده را توصیف کن.' }, 'a1-free-time': { title: 'چیزهایی که دوست دارم', objective: 'درباره سرگرمی‌ها و علاقه‌ها صحبت کن.' },
  'a1-at-the-cafe': { title: 'در کافه', objective: 'یک نوشیدنی یا خوراکی را مؤدبانه سفارش بده.' }, 'a1-shopping': { title: 'خرید با اعتمادبه‌نفس', objective: 'درباره قیمت، اندازه و محصول سؤال کن.' },
  'a1-directions': { title: 'پیداکردن مسیر', objective: 'مسیر ساده را بپرس و درک کن.' }, 'a1-travel-day': { title: 'یک روز سفر روان', objective: 'گفت‌وگوهای ساده فرودگاه و ایستگاه را مدیریت کن.' },
  'a2-weekend-plans': { title: 'برنامه آخر هفته', objective: 'فعالیتی پیشنهاد بده و زمان را هماهنگ کن.' }, 'a2-invitations': { title: 'دعوت و پاسخ', objective: 'دعوت کن، بپذیر یا مؤدبانه رد کن.' },
  'a2-stories': { title: 'یک داستان کوتاه بگو', objective: 'رویدادی به‌یادماندنی را به‌ترتیب تعریف کن.' }, 'a2-experiences': { title: 'تجربه‌ها را به اشتراک بگذار', objective: 'بدون گفتن زمان مشخص درباره تجربه زندگی حرف بزن.' },
  'a2-work-conversations': { title: 'گفت‌وگوهای کاری روشن', objective: 'توضیح بیشتر بخواه و قدم بعدی را تأیید کن.' }, 'a2-solving-problems': { title: 'حل مؤدبانه مشکل', objective: 'مشکل را توضیح بده، کمک بخواه و راه‌حل پیدا کن.' },
  'a2-opinions': { title: 'نظرت را بگو', objective: 'نظر بده و محترمانه موافقت یا مخالفت کن.' }, 'a2-next-steps': { title: 'فصل بعدی را برنامه‌ریزی کن', objective: 'هدف‌ها و قدم‌های رسیدن به آن‌ها را توضیح بده.' },
};

export function translate(locale: Locale, key: string, values: Values = {}) {
  const template = (locale === 'fa' ? fa[key] : en[key]) ?? en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export function courseText(locale: Locale, kind: 'module' | 'lesson', id: string, field: 'title' | 'description' | 'outcome' | 'objective', fallback: string) {
  if (locale !== 'fa') return fallback;
  const copy = kind === 'module' ? persianModules[id] : persianLessons[id];
  return copy?.[field as keyof typeof copy] ?? fallback;
}
